framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        transports:
            sync: 'sync://'
            async: 'in-memory://'

        routing:
            'Application\Command\UpdateExchangeRates\UpdateExchangeRatesCommand': sync
            'Application\Query\FindCurrenciesForDate\FindCurrenciesForDateQuery': sync
            'Application\Query\FindCurrenciesCodes\FindCurrenciesCodesQuery': sync
            'Application\Query\ExchangeCurrencyToAnotherOne\ExchangeCurrencyToAnotherOneQuery': sync
